COMMANDS_HELP_MESSAGE = 'To see all the avaliable commands send [/help]'
EXIT_MESSAGE = '/disconnect'
SEND_FILE_MESSAGE = '/sendfile '
SEND_TO_MESSAGE = '/sendto '
SHOW_COMMANDS_MESSAGE = '/help'

MESSAGE_PREFIX = '>> '
INCOMING_MESSAGE_PREFIX = ''
INITIATE_MESSAGE = 'Strting the client'
SERVER_MESSAGE_PREFIX = 'Server: '
CONNECTED_MESSAGE = 'Connected to: '
LEAVE_MESSAGE_INFO = f'If you want to leave the server send {EXIT_MESSAGE}'
CONNECTION_ERROR_MESSAGE = 'Connection failed because'
NAME_MESSAGE = 'Hey!! Please enter your name: '
SENDING_FILE_MESSAGE = 'Sending file'